add check-graylog-streams script
sensu-plugins/sensu-plugins-graylog pull request #6
Opened 2017-03-16 18:34 UTC by nathanhruby

## Pull Request Checklist

**Is this in reference to an existing issue?**  No

#### General

- [x] Update Changelog following the conventions laid out on [Keep A Changelog](http://keepachangelog.com/)

- [x] Update README with any necessary configuration snippets

- [x] Binstubs are created if needed

- [x] RuboCop passes

- [x] Existing tests pass 

#### Purpose
This adds an additional check called "check-graylog-streams.rb" that looks for and alerts on paused streams.  Graylog will automatically pause a stream when the processing time for it gets too long as a defense measure (long GC, expensive criteria, etc..).   

Since streams are applied only at event index time, there's no way to retroactively apply them after the stream is unpaused, so quick notification and repair is important.

#### Known Compatibility Issues
None known, this is new script.

2017-03-23 14:19 UTC, nathanhruby commented
gentle nudge for review

2017-03-24 06:49 UTC, eheydrick requested changes

2017-03-24 06:49 UTC, eheydrick commented on bin/check-graylog-streams.rb
> +require 'rubygems' if RUBY_VERSION < '1.9.0'
remove this. we don't support Ruby 1.8.7 anymore.

2017-03-24 16:07 UTC, nathanhruby commented
Derp, yes, thank you.  This came from a CentOS 5 system on ruby 1.8.7 and I breezed past that when porting.  Upstreaming is hard.

2017-04-21 18:57 UTC, nathanhruby commented
nudge for re-review

2017-04-25 14:12 UTC, eheydrick approved these changes

2017-04-25 14:13 UTC, merged

2017-04-25 14:13 UTC, eheydrick commented
LGTM. Thanks!

2017-04-25 14:34 UTC, nathanhruby commented
Thank you!