Add protocol option to all queries
sensu-plugins/sensu-plugins-graylog pull request #9
Opened 2017-12-04 16:41 UTC by Narayanan170

## Pull Request Checklist

**Is this in reference to an existing issue?**

#### General

- [ ] Update Changelog following the conventions laid out on [Keep A Changelog](http://keepachangelog.com/)

- [ ] Update README with any necessary configuration snippets

- [ ] Binstubs are created if needed

- [ ] RuboCop passes

- [ ] Existing tests pass

#### New Plugins

- [ ] Tests

- [ ] Add the plugin to the README

- [ ] Does it have a complete header as outlined [here](http://sensu-plugins.io/docs/developer_guidelines.html#coding-style)

#### Purpose

#### Known Compatibility Issues

2017-12-04 17:00 UTC, Narayanan170 commented
This is a pull request resolving issue #8

2017-12-06 06:54 UTC, majormoses commented
Thanks for your contribution to Sensu plugins! Without people like you submitting PRs we couldn't run the project. I will review it shortly.

2017-12-06 07:08 UTC, majormoses requested changes
Overall this looks great one minor changelog tweak and a [testing artifact](https://github.com/sensu-plugins/community/blob/master/PULL_REQUEST_PROCESS.md#7-testing-artifacts) is all I need and to get this merged and released.

2017-12-06 07:08 UTC, majormoses commented on CHANGELOG.md
> +### Changed
This should be `### Added` as that is a new feature the ability to change the protocol.

2017-12-06 07:08 UTC, majormoses commented on CHANGELOG.md
> +- Add protocol option which can be passed asn an argument to specify which protocol to use
> asn an argument

looks like a typo

2017-12-06 07:08 UTC, majormoses commented on bin/check-graylog-buffers.rb
> +         short: '-proto',
I am actually not sure if short is ok with multi char short args. Have you tested this? Usually short options single chars that can be chained together like `tar -xvf` that is not a single arg but actually 3 of them.

2017-12-06 07:08 UTC, majormoses commented on bin/check-graylog-buffers.rb
> +         default: 'http'
As much as I feel `https` should be the default I agree that the breaking change would be unwarranted right now.

2017-12-21 11:54 UTC, Narayanan170 commented
I would also like to see `https` as a default, but that is an expensive change version wise... I am now working on a testing artifact.

2017-12-21 13:41 UTC, Narayanan170 commented
I don't actually see how can I test this except for unit testing, but that would be testing the mixlib-cli gem... If you have a better idea for this, I would love to hear it :)

2017-12-21 17:54 UTC, majormoses commented
Well there are a couple options:
- unit testing
- integration testing
- manual testing

I would suggest you read the following articles where I outline the types of testing and go in depth with integration testing:
- https://blog.sensuapp.org/our-approach-to-testing-sensu-plugins-869260eba94c
- https://blog.sensuapp.org/writing-sensu-plugin-tests-with-test-kitchen-and-serverspec-b646d2eeee51

The easiest is a manual test, just run the check you would have run via sensu in cli and capture the input and output in a gist.

2018-01-02 19:36 UTC, nathanhruby commented
The tests in check-graylog-streams_spec.rb could be used as an example for checking the args and stubbing out the actual call to make sure it is used as intended.

2018-01-03 03:25 UTC, majormoses requested changes
A few more things I noticed that could be improved:
- drop the `-s` option as the name does not make sense and `-p` is used for `port`
- specify the available options for `protocol` like [this](https://github.com/sensu-plugins/sensu-plugins-redis/blob/2.3.2/lib/redis_client_options.rb#L75)

2018-01-03 03:25 UTC, majormoses commented on bin/check-graylog2-alive.rb
> +         short: '-s',
let's drop the `-s` as it no longer makes sense and `-p` is usually `port`

2018-01-03 03:25 UTC, majormoses commented on bin/check-graylog-streams.rb
> +         short: '-s',
let's drop the `-s` as it no longer makes sense and `-p` is usually `port`

2018-01-03 03:25 UTC, majormoses commented on bin/check-graylog-buffers.rb
> +         short: '-s',
let's drop the `-s` as it no longer makes sense and `-p` is usually `port`

2018-01-03 03:25 UTC, majormoses commented on bin/metrics-graylog.rb
> +         short: '-s',
let's drop the `-s` as it no longer makes sense and `-p` is usually `port`

2018-01-20 20:32 UTC, majormoses commented
I have made the requested modifications if someone can provide either a manal or automated testing artifact I am :+1: to merge this.

2018-02-13 17:08 UTC, majormoses commented
@nathanhruby any chance you have a graylog that we can test against? I don't see how this PR is the culprit of https://github.com/sensu-plugins/sensu-plugins-graylog/issues/8#issuecomment-365294851 but it does mean we need to ensure that we have a test before I am OK with merging this.

2018-02-13 17:29 UTC, nathanhruby commented
I don't work at a place with graylog anymore, but I might have some time later this week to spin up a test cluster in a docker as test of something else I am doing.

2018-02-17 04:28 UTC, majormoses commented
I can confirm this works:
```
$ bundle exec ./bin/check-graylog2-alive.rb --protocol https --host graylog.$DOMAIN.$TLD --username babrams --password $(cat creds) --port 443 --apipath /api
CheckGraylog2Alive OK: Graylog2 server is: running/true/alive
```

2018-02-17 04:29 UTC, merged

2018-02-17 04:43 UTC, majormoses commented
released: https://rubygems.org/gems/sensu-plugins-graylog/versions/1.3.0